/**
 * @export
 * @typedef {ButtonTitle}
 */
export type ButtonTitle =
  | ' '
  | 'AC'
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | '0'
  | ','
  | '÷'
  | '×'
  | '−'
  | '+'
  | '=';

/**
 * Model for the calculator
 *
 * @export
 * @interface Calculator
 * @typedef {Calculator}
 */
export interface Calculator {
  /**
   * UUID of the calculator.  
   * The UUID is used to identify the calculator Instants.  
   * The UUID is generated by the function {@link generate_UUIDv4}  
   * The UUID is a version 4.  
   *
   * @type {string}
   */
  uuid: string;
  /**
   * The input of the calculator.
   *
   * @type {string}
   */
  input: string;
  /**
   * The name of the calculator.  
   * The name is optional.  
   *
   * @type {string}
   */
  name?: string;
}
